project:
  type: website

website:
  title: 'df_blog'
  navbar:
    background: '#330c6b'
    foreground: '#EEEEEE'
    right:
      - about.qmd
      - icon: github
        href: https://github.com/davidfoord1/analysis-blog
format:
  html:
    theme: minty
    css: styles.css



